repos:
  - repo: https://github.com/qiaojunfeng/pre-commit-julia-format
    rev: v0.2.0
    hooks:
      - id: julia-format
        args: [--project=.]  
        exclude: >-
          (?x)^(
              attic/.*|
              docs/.*|
              inputs/.*|
              src/.*|
              test/.*\.md|
              test/.*\.toml|
              test/.*\.json|
          )$
