name: Documentation

on:
  push:
    branches:
      - main  # Or your default branch
  pull_request:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.7'  # Choose the version of Julia you want to use

      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.instantiate()'

      - name: Build and deploy documentation
        run: julia --project=docs/ docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This token is automatically provided by GitHub

