name: Format suggestions

on:
  push:
    branches:
      - main
      - dev
      - refactor
      - 'releases/**'
    tags: '*'
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
  release:

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
            
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python and install pre-commit
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit  # Install pre-commit

      - name: Install pre-commit hooks
        run: pre-commit install  # Install hooks defined in .pre-commit-config.yaml

      - name: Clean pre-commit cache
        run: pre-commit clean  # Clean the pre-commit cache

      - name: Check .pre-commit-config.yaml
        run: cat .pre-commit-config.yaml  # Check the content of the config file

      - name: Run Julia formatter
        uses: julia-actions/julia-format@v3
        with:
          version: '1'  # Set `version` to '1.0.54' if you need to use JuliaFormatter.jl v1.0.54 (default: '1')
          suggestion-label: 'format-suggest'  # leave this unset or empty to show suggestions for all PRs
