---
name: Format suggestions
on:
  push:
    branches:
      - main
      - dev
      - releases/**
    tags: "*"
    paths-ignore:
      - attic/**
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
    paths-ignore:
      - attic/**
  release: null
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python and install pre-commit
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit  # Install pre-commit
      - name: Install pre-commit hooks
        run: pre-commit install
      - name: Clean pre-commit cache
        run: pre-commit clean
      - name: Check .pre-commit-config.yaml
        run: cat .pre-commit-config.yaml
      - name: List files in src, test, attic
        run: |
          echo "Files in src:"
          find src
          echo "Files in test:"
          find test
          echo "Files in attic:"
          find attic
      - name: List all files being checked by pre-commit
        run: |
          git ls-files
          pre-commit run --all-files --verbose
      - name: Run Julia formatter
        uses: julia-actions/julia-format@v3
        with:
          version: "1"
          suggestion-label: format-suggest
