name: Format suggestions
on:
  push:
    branches:
      - main
      - dev
      - 'releases/**'
    tags: '*'
  pull_request:
    # this argument is not required if you don't use the `suggestion-label` input
    types: [ opened, reopened, synchronize, labeled, unlabeled ]
  release:
  
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Install pre-commit hooks
        run: pre-commit install

      - name: Clear pre-commit cache
        run: pre-commit clean
        
      - name: Run Julia formatter
        uses: julia-actions/julia-format@v3
        with:
          version: '1' # Set `version` to '1.0.54' if you need to use JuliaFormatter.jl v1.0.54 (default: '1')
          suggestion-label: 'format-suggest' # leave this unset or empty to show suggestions for all PRs
